# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/johnny/Documents/Repositories/CS352/shell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/johnny/Documents/Repositories/CS352/shell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/johnny/Documents/Repositories/CS352/shell/CMakeFiles /home/johnny/Documents/Repositories/CS352/shell//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/johnny/Documents/Repositories/CS352/shell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/johnny/Documents/Repositories/CS352/shell/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shell352

# Build rule for target.
shell352: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shell352
.PHONY : shell352

# fast build rule for target.
shell352/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shell352.dir/build.make CMakeFiles/shell352.dir/build
.PHONY : shell352/fast

#=============================================================================
# Target rules for targets named buongiorno

# Build rule for target.
buongiorno: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 buongiorno
.PHONY : buongiorno

# fast build rule for target.
buongiorno/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/build
.PHONY : buongiorno/fast

src/buongiorno/builtin.o: src/buongiorno/builtin.c.o

.PHONY : src/buongiorno/builtin.o

# target to build an object file
src/buongiorno/builtin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/builtin.c.o
.PHONY : src/buongiorno/builtin.c.o

src/buongiorno/builtin.i: src/buongiorno/builtin.c.i

.PHONY : src/buongiorno/builtin.i

# target to preprocess a source file
src/buongiorno/builtin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/builtin.c.i
.PHONY : src/buongiorno/builtin.c.i

src/buongiorno/builtin.s: src/buongiorno/builtin.c.s

.PHONY : src/buongiorno/builtin.s

# target to generate assembly for a file
src/buongiorno/builtin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/builtin.c.s
.PHONY : src/buongiorno/builtin.c.s

src/buongiorno/builtin/builtin_exit.o: src/buongiorno/builtin/builtin_exit.c.o

.PHONY : src/buongiorno/builtin/builtin_exit.o

# target to build an object file
src/buongiorno/builtin/builtin_exit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/builtin/builtin_exit.c.o
.PHONY : src/buongiorno/builtin/builtin_exit.c.o

src/buongiorno/builtin/builtin_exit.i: src/buongiorno/builtin/builtin_exit.c.i

.PHONY : src/buongiorno/builtin/builtin_exit.i

# target to preprocess a source file
src/buongiorno/builtin/builtin_exit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/builtin/builtin_exit.c.i
.PHONY : src/buongiorno/builtin/builtin_exit.c.i

src/buongiorno/builtin/builtin_exit.s: src/buongiorno/builtin/builtin_exit.c.s

.PHONY : src/buongiorno/builtin/builtin_exit.s

# target to generate assembly for a file
src/buongiorno/builtin/builtin_exit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/builtin/builtin_exit.c.s
.PHONY : src/buongiorno/builtin/builtin_exit.c.s

src/buongiorno/command_utilities.o: src/buongiorno/command_utilities.c.o

.PHONY : src/buongiorno/command_utilities.o

# target to build an object file
src/buongiorno/command_utilities.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/command_utilities.c.o
.PHONY : src/buongiorno/command_utilities.c.o

src/buongiorno/command_utilities.i: src/buongiorno/command_utilities.c.i

.PHONY : src/buongiorno/command_utilities.i

# target to preprocess a source file
src/buongiorno/command_utilities.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/command_utilities.c.i
.PHONY : src/buongiorno/command_utilities.c.i

src/buongiorno/command_utilities.s: src/buongiorno/command_utilities.c.s

.PHONY : src/buongiorno/command_utilities.s

# target to generate assembly for a file
src/buongiorno/command_utilities.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/buongiorno.dir/build.make CMakeFiles/buongiorno.dir/src/buongiorno/command_utilities.c.s
.PHONY : src/buongiorno/command_utilities.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shell352.dir/build.make CMakeFiles/shell352.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shell352.dir/build.make CMakeFiles/shell352.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shell352.dir/build.make CMakeFiles/shell352.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... buongiorno"
	@echo "... shell352"
	@echo "... src/buongiorno/builtin.o"
	@echo "... src/buongiorno/builtin.i"
	@echo "... src/buongiorno/builtin.s"
	@echo "... src/buongiorno/builtin/builtin_exit.o"
	@echo "... src/buongiorno/builtin/builtin_exit.i"
	@echo "... src/buongiorno/builtin/builtin_exit.s"
	@echo "... src/buongiorno/command_utilities.o"
	@echo "... src/buongiorno/command_utilities.i"
	@echo "... src/buongiorno/command_utilities.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/johnny/Documents/Repositories/CS352/shell/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

